default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: noteapp_development
  username: eclipton
  password: 1234
  port: 5432
  host: localhost

test:
  <<: *default
  database: noteapp_test
  username: eclipton
  password: 1234
  port: 5432
  host: localhost

production:
  <<: *default
  database: noteapp_production
  url: <%= ENV["MY_APP_DATABASE_URL"] %>